### PR TITLE
.net core 3.1 support

### PR DESCRIPTION
**Pull request by Sverdel**
Hi!
I found out that AnonymousIdentity can't work with .net core 3.1, because of changes in IdentityServer4 library - some extension methods were move into other namespace

There are some changes to fix this problem

### CODE REVIEW

**Review by dkindev — COMMENTED** [review]
@Sverdel Hi. Sorry for the long reply. You forgot to change the target framework in test projects.

**Comment by Sverdel** [comment]
Oh, sorry! I must've missed test projects in unstaged files. I've just fixed it. All tests are green, btw)

**Review by dkindev — APPROVED** [review]
@Sverdel Thanks you for the contribution.

**Comment by dkindev** [comment]
@Sverdel I updated the nuget package. Enjoy =)

**Pull request merged**
